# Generated by Django 4.1.7 on 2024-04-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medapplicant',
            table='medapplicants',
        ),
    ]
