# Generated by Django 5.0.3 on 2024-04-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0002_remove_medapplicant_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medapplicant',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
