# Generated by Django 5.0.3 on 2024-04-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0003_alter_medapplicant_registration_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medapplicant',
            table='medapplicants',
        ),
    ]
