    # Generated by Django 4.1.7 on 2024-04-21 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0003_medapplicant_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedAnswers',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('answer_image', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('selection_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'medanswers',
            },
        ),
        migrations.CreateModel(
            name='MedQuestions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_image', models.TextField(blank=True, null=True)),
                ('question_category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'medquestions',
            },
        ),
        migrations.CreateModel(
            name='MedTestTemplate',
            fields=[
                ('test_template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.TextField()),
                ('template_description', models.TextField()),
            ],
            options={
                'db_table': 'med_test_templates',
            },
        ),
        migrations.CreateModel(
            name='StudentTests',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_date', models.DateTimeField(auto_now_add=True, db_column='test_date')),
                ('score', models.IntegerField(db_column='score')),
                ('total_possible_score', models.IntegerField(db_column='total_possible_score')),
                ('student_id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test_template_id', models.ForeignKey(db_column='test_template_id', on_delete=django.db.models.deletion.CASCADE, to='helloapp.medtesttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswers',
            fields=[
                ('student_answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='helloapp.medquestions')),
                ('selected_answer', models.ForeignKey(db_column='selected_answer_id', on_delete=django.db.models.deletion.CASCADE, to='helloapp.medanswers')),
                ('test', models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='helloapp.studenttests')),
            ],
            options={
                'db_table': 'student_answers',
            },
        ),
        migrations.AddField(
            model_name='medanswers',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='helloapp.medquestions'),
        ),
    ]
