# Generated by Django 4.2.10 on 2024-05-11 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0004_medanswers_medquestions_medtesttemplate_studenttests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_ids', models.JSONField(default=list)),
                ('user_answers', models.JSONField(default=list)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloapp.medquestions')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloapp.studenttests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_question_answers',
            },
        ),
    ]
