# Generated by Django 4.2.10 on 2024-05-11 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0008_userquestionanswers_incorrect_answers_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medanswers',
            old_name='question_id',
            new_name='question',
        ),
    ]
