# Generated by Django 4.2.10 on 2024-05-11 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0009_rename_question_id_medanswers_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medanswers',
            name='question',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='helloapp.medquestions'),
        ),
    ]
